### ISSUE TITLE
Millions of people cant just install flutter toolkit and start porting this over

### ISSUE THREAD

**Issue by fisforfaheem** [miickel/flutter_particle_clock#6] opened 2020-03-04 15:56 UTC
Please also provide an .exe file so people could see what amazing thing u created that got you the prize!

**Comment by miickel** [comment] 2020-03-05 16:39
Duplicate of #2 and #5 

Please don't open any more issues about this, you will have to try doing it yourself.

**Closed as completed by miickel** 2020-03-05 16:39 UTC
